"""
Synthetic Data Generator
Creates 100 realistic startup records (50 positive YC + 50 negative non-YC)
Based on actual YC and Wellfound data structure from images
"""

import pandas as pd
from typing import List, Dict
from utils.logger import log

class SyntheticDataGenerator:
    """Generate realistic synthetic startup data."""
    
    # ===== POSITIVE DATA (YC Companies - Label: 1) =====
    YC_COMPANIES_SYNTHETIC = [
        {
            "name": "Airbnb",
            "description": "Book accommodations around the world. We connect people to unique travel experiences at any price point in more than 33,000 cities and 192 countries. Our mission is to create a world where anyone can belong anywhere.",
            "industry": "Travel Tech",
            "founded_year": 2008,
            "batch": "Winter 2009",
            "status": "Public",
            "team_size": 6132,
            "location": "San Francisco, CA",
            "founders": ["Brian Chesky", "Nathan Blecharczyk", "Joe Gebbia"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Stripe",
            "description": "Online payment processing platform. We enable businesses of all sizes to accept payments and move money globally. Stripe is the backbone of the internet economy, processing hundreds of billions in transactions annually.",
            "industry": "FinTech",
            "founded_year": 2010,
            "batch": "Summer 2010",
            "status": "Private",
            "team_size": 3200,
            "location": "San Francisco, CA",
            "founders": ["Patrick Collison", "John Collison"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Dropbox",
            "description": "Cloud storage and file synchronization service. We help millions of people store, sync, and share files securely. Our mission is to unlock human potential by designing a more enlightened way of working.",
            "industry": "Cloud Storage",
            "founded_year": 2008,
            "batch": "Summer 2007",
            "status": "Public",
            "team_size": 2500,
            "location": "San Francisco, CA",
            "founders": ["Drew Houston", "Arash Ferdowski"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Airbnb Clone - TravelStay",
            "description": "Next generation accommodation marketplace connecting travelers with unique properties. We are disrupting the $1 trillion travel industry with AI-powered personalization and seamless booking experience.",
            "industry": "Travel Tech",
            "founded_year": 2022,
            "batch": "Winter 2023",
            "status": "Private",
            "team_size": 85,
            "location": "San Francisco, CA",
            "founders": ["Sarah Chen", "Michael Park"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "DoorDash",
            "description": "Restaurant delivery platform. We are building the delivery infrastructure for commerce. Through DoorDash, people get the food they love from their favorite local restaurants.",
            "industry": "E-commerce",
            "founded_year": 2013,
            "batch": "Summer 2013",
            "status": "Public",
            "team_size": 4500,
            "location": "San Francisco, CA",
            "founders": ["Tony Xu", "Stanley Tang", "Evan Moore"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Figma",
            "description": "Collaborative design tool. Figma is the place where design happens. We are building the first browser-based design tool with real-time collaboration for teams to design better products together.",
            "industry": "Design Tech",
            "founded_year": 2016,
            "batch": "N/A",
            "status": "Private",
            "team_size": 1200,
            "location": "San Francisco, CA",
            "founders": ["Dylan Field", "Evan Wallace"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Slack",
            "description": "Business communication platform. Slack transforms how people work together. We bring all your communication together in one place to make teams more productive and connected.",
            "industry": "SaaS",
            "founded_year": 2011,
            "batch": "N/A",
            "status": "Public",
            "team_size": 2300,
            "location": "San Francisco, CA",
            "founders": ["Stewart Butterfield"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Twilio",
            "description": "Cloud communications platform. We enable developers to build communications into their applications. Twilio powers the future of business communications for millions of users worldwide.",
            "industry": "SaaS",
            "founded_year": 2008,
            "batch": "Summer 2008",
            "status": "Public",
            "team_size": 1800,
            "location": "San Francisco, CA",
            "founders": ["Jeff Lawson"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Notion",
            "description": "All-in-one workspace. Notion is where work happens. We are building the all-in-one workspace for notes, tasks, wikis, and databases to help teams work more effectively together.",
            "industry": "Productivity",
            "founded_year": 2016,
            "batch": "N/A",
            "status": "Private",
            "team_size": 650,
            "location": "San Francisco, CA",
            "founders": ["Ivan Zhao"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Instacart",
            "description": "Grocery delivery service. We connect customers with restaurant and food delivery services. Our mission is to empower local economies by enabling people to get what they need.",
            "industry": "E-commerce",
            "founded_year": 2012,
            "batch": "Summer 2012",
            "status": "Private",
            "team_size": 3000,
            "location": "San Francisco, CA",
            "founders": ["Apoorva Mehta"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Uber",
            "description": "Ride-sharing and delivery platform. We reimagine the way people and things move around cities. Uber is the platform that makes transportation accessible.",
            "industry": "Transportation",
            "founded_year": 2009,
            "batch": "N/A",
            "status": "Public",
            "team_size": 6500,
            "location": "San Francisco, CA",
            "founders": ["Travis Kalanick", "Garrett Camp"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Canva",
            "description": "Design platform for everyone. Canva empowers the world to design. We are democratizing design by making professional design accessible to everyone without special training.",
            "industry": "Design Tech",
            "founded_year": 2013,
            "batch": "N/A",
            "status": "Private",
            "team_size": 800,
            "location": "Sydney, Australia",
            "founders": ["Melanie Perkins"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "OpenAI",
            "description": "AI research and deployment company. We are conducting research to ensure artificial general intelligence benefits all of humanity. OpenAI develops safe and beneficial AI systems.",
            "industry": "AI/ML",
            "founded_year": 2015,
            "batch": "N/A",
            "status": "Private",
            "team_size": 900,
            "location": "San Francisco, CA",
            "founders": ["Sam Altman", "Elon Musk"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Coursera",
            "description": "Online learning platform. We aim to provide universal access to world-class education. Coursera partners with universities and companies to offer courses on almost every subject.",
            "industry": "EdTech",
            "founded_year": 2012,
            "batch": "N/A",
            "status": "Public",
            "team_size": 1500,
            "location": "Mountain View, CA",
            "founders": ["Andrew Ng", "Daphne Koller"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Palantir",
            "description": "Big data analytics platform. We transform data into actionable intelligence. Palantir's software is used by the world's most important institutions to uncover the truth in data.",
            "industry": "Data Analytics",
            "founded_year": 2003,
            "batch": "N/A",
            "status": "Public",
            "team_size": 3800,
            "location": "Denver, CO",
            "founders": ["Peter Thiel", "Alex Karp"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Datadog",
            "description": "Monitoring and analytics platform. We help organizations optimize their cloud infrastructure. Datadog monitors applications, infrastructure, and user experience across the entire stack.",
            "industry": "DevOps",
            "founded_year": 2010,
            "batch": "Summer 2010",
            "status": "Public",
            "team_size": 2200,
            "location": "New York, NY",
            "founders": ["Olivier Pomel", "Alexis Lê-Quôc"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Zapier",
            "description": "Workflow automation platform. We connect your apps and automate workflows. Zapier helps teams accomplish more by automating repetitive tasks across your favorite apps.",
            "industry": "SaaS",
            "founded_year": 2011,
            "batch": "Summer 2011",
            "status": "Private",
            "team_size": 450,
            "location": "San Francisco, CA",
            "founders": ["Wade Foster"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "GitLab",
            "description": "DevOps platform. We are the DevOps platform delivering value throughout the software development and operations lifecycle. GitLab integrates all the tools needed for software development.",
            "industry": "DevOps",
            "founded_year": 2013,
            "batch": "N/A",
            "status": "Public",
            "team_size": 1800,
            "location": "San Francisco, CA",
            "founders": ["Sid Sijbrandij"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Loom",
            "description": "Video messaging platform. Loom is the easiest way to communicate using instant video messages. Record your screen, share instantly, and save time on meetings.",
            "industry": "Productivity",
            "founded_year": 2016,
            "batch": "Winter 2016",
            "status": "Private",
            "team_size": 250,
            "location": "San Francisco, CA",
            "founders": ["Joe Thomas"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Guidepoint",
            "description": "Expert network platform. We connect professionals with experts for insights. Guidepoint enables companies to tap into expert knowledge for better decision making.",
            "industry": "B2B SaaS",
            "founded_year": 2012,
            "batch": "Winter 2012",
            "status": "Private",
            "team_size": 800,
            "location": "New York, NY",
            "founders": ["Shayle Compton"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Segment",
            "description": "Customer data platform. We collect, clean, and activate customer data. Segment is the leading Customer Data Platform helping businesses make data-driven decisions.",
            "industry": "Data Analytics",
            "founded_year": 2011,
            "batch": "Summer 2011",
            "status": "Public",
            "team_size": 1000,
            "location": "San Francisco, CA",
            "founders": ["Peter Reinhardt"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Airtable",
            "description": "Low-code database platform. Airtable combines the simplicity of a spreadsheet with the power of a database. We are democratizing software creation for millions of users.",
            "industry": "SaaS",
            "founded_year": 2012,
            "batch": "Summer 2012",
            "status": "Private",
            "team_size": 800,
            "location": "San Francisco, CA",
            "founders": ["Howie Liu"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Amplitude",
            "description": "Product analytics platform. We help companies build better products with data-driven insights. Amplitude enables digital leaders to understand user behavior and drive growth.",
            "industry": "Analytics",
            "founded_year": 2012,
            "batch": "Summer 2012",
            "status": "Public",
            "team_size": 900,
            "location": "San Francisco, CA",
            "founders": ["Curtis Lee", "Spencer Kimball"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Webpack AI",
            "description": "AI-powered developer tools. We use AI to help developers code faster and better. Our tools integrate seamlessly into existing development workflows.",
            "industry": "Developer Tools",
            "founded_year": 2023,
            "batch": "Winter 2023",
            "status": "Private",
            "team_size": 45,
            "location": "San Francisco, CA",
            "founders": ["Alex Kumar", "Priya Singh"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "CloudFlare",
            "description": "Web performance and security company. We make the internet faster and safer. CloudFlare protects and accelerates web applications for millions of users worldwide.",
            "industry": "Infrastructure",
            "founded_year": 2009,
            "batch": "Summer 2010",
            "status": "Public",
            "team_size": 2500,
            "location": "San Francisco, CA",
            "founders": ["Matthew Prince"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Retool",
            "description": "Low-code internal tools platform. We help organizations build internal tools 10x faster. Retool is the fastest way to build business software.",
            "industry": "Developer Tools",
            "founded_year": 2019,
            "batch": "Winter 2019",
            "status": "Private",
            "team_size": 200,
            "location": "San Francisco, CA",
            "founders": ["David Hsu"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Superhuman",
            "description": "High-speed email client. We revolutionize how people work with email. Superhuman helps professionals reclaim time by making email faster and more efficient.",
            "industry": "Productivity",
            "founded_year": 2015,
            "batch": "Winter 2015",
            "status": "Private",
            "team_size": 150,
            "location": "San Francisco, CA",
            "founders": ["Rahul Vohra"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Craft.co",
            "description": "B2B database platform. We provide the most accurate and complete B2B data. Craft is the leading platform for finding and understanding companies.",
            "industry": "B2B Data",
            "founded_year": 2017,
            "batch": "Summer 2017",
            "status": "Private",
            "team_size": 400,
            "location": "San Francisco, CA",
            "founders": ["Micah Alcorn"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "Zapier Clone - FlowMate",
            "description": "Automation workflow builder connecting business applications. We simplify business processes through intelligent automation and seamless integrations.",
            "industry": "SaaS",
            "founded_year": 2023,
            "batch": "Summer 2023",
            "status": "Private",
            "team_size": 65,
            "location": "Austin, TX",
            "founders": ["John Martinez", "Lisa Chen"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "ByteDance AI Tools",
            "description": "AI-powered content creation suite. We democratize AI for content creators and businesses. Our tools help creators produce professional content effortlessly.",
            "industry": "AI/ML",
            "founded_year": 2022,
            "batch": "Spring 2023",
            "status": "Private",
            "team_size": 120,
            "location": "Beijing, China",
            "founders": ["Wei Song", "Alex Zhang"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "FinFlow Platform",
            "description": "Financial operations automation. We streamline financial workflows for growing companies. FinFlow reduces manual processes and improves financial accuracy.",
            "industry": "FinTech",
            "founded_year": 2022,
            "batch": "Winter 2022",
            "status": "Private",
            "team_size": 95,
            "location": "New York, NY",
            "founders": ["Michael Torres", "Emily Watson"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "HRFlow Analytics",
            "description": "AI-powered HR analytics platform. We help organizations make better people decisions. Our platform provides insights into hiring, retention, and employee performance.",
            "industry": "HR Tech",
            "founded_year": 2020,
            "batch": "Summer 2020",
            "status": "Private",
            "team_size": 110,
            "location": "San Francisco, CA",
            "founders": ["Robert Chen"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "CloudSecure Pro",
            "description": "Cloud security platform for enterprises. We protect cloud infrastructure from threats. CloudSecure provides comprehensive security across AWS, Azure, and GCP.",
            "industry": "Cybersecurity",
            "founded_year": 2021,
            "batch": "Fall 2021",
            "status": "Private",
            "team_size": 140,
            "location": "San Jose, CA",
            "founders": ["David Patel", "Anita Sharma"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "MedAssist AI",
            "description": "AI diagnostics platform for healthcare. We help medical professionals make better diagnoses. Our AI analyzes medical imaging with high accuracy.",
            "industry": "HealthTech",
            "founded_year": 2021,
            "batch": "Winter 2021",
            "status": "Private",
            "team_size": 85,
            "location": "Boston, MA",
            "founders": ["Dr. James Lee"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "EduConnect Pro",
            "description": "Online learning marketplace connecting students with tutors. We revolutionize education through personalized learning. EduConnect makes quality education accessible to all.",
            "industry": "EdTech",
            "founded_year": 2020,
            "batch": "Spring 2020",
            "status": "Private",
            "team_size": 200,
            "location": "San Francisco, CA",
            "founders": ["Sarah Johnson"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "LogiFlow",
            "description": "Supply chain optimization platform. We use AI to optimize logistics operations. LogiFlow helps companies reduce delivery costs and improve efficiency.",
            "industry": "Logistics",
            "founded_year": 2021,
            "batch": "Summer 2021",
            "status": "Private",
            "team_size": 180,
            "location": "Los Angeles, CA",
            "founders": ["Carlos Mendez"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "GreenEnergyHub",
            "description": "Renewable energy marketplace. We connect businesses with green energy solutions. GreenEnergyHub is accelerating the transition to sustainable energy.",
            "industry": "Clean Energy",
            "founded_year": 2019,
            "batch": "Summer 2019",
            "status": "Private",
            "team_size": 160,
            "location": "Boulder, CO",
            "founders": ["Tom Williams"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "ResearchAI",
            "description": "AI research tool for academics. We accelerate scientific discovery through AI. ResearchAI helps researchers find and analyze papers efficiently.",
            "industry": "Research Tech",
            "founded_year": 2022,
            "batch": "Fall 2022",
            "status": "Private",
            "team_size": 75,
            "location": "Stanford, CA",
            "founders": ["Professor Alex Kumar"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "PropertyTech AI",
            "description": "Real estate analytics platform. We help investors identify property opportunities. PropertyTech uses ML to predict market trends and property values.",
            "industry": "Real Estate",
            "founded_year": 2020,
            "batch": "Spring 2020",
            "status": "Private",
            "team_size": 130,
            "location": "San Francisco, CA",
            "founders": ["Victoria Lee"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "LawyerBot",
            "description": "Legal tech platform powered by AI. We make legal services accessible and affordable. LawyerBot provides automated contract review and legal assistance.",
            "industry": "Legal Tech",
            "founded_year": 2021,
            "batch": "Winter 2021",
            "status": "Private",
            "team_size": 95,
            "location": "New York, NY",
            "founders": ["Jennifer Rodriguez"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "FarmTech Solutions",
            "description": "Agricultural technology platform. We help farmers optimize crop yields. FarmTech uses IoT and AI for precision agriculture.",
            "industry": "AgTech",
            "founded_year": 2020,
            "batch": "Summer 2020",
            "status": "Private",
            "team_size": 110,
            "location": "Ames, IA",
            "founders": ["David Zhang"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "GameStudio Engine",
            "description": "Game development platform. We democratize game creation. GameStudio Engine helps creators build games without coding.",
            "industry": "Gaming",
            "founded_year": 2021,
            "batch": "Summer 2021",
            "status": "Private",
            "team_size": 180,
            "location": "Los Angeles, CA",
            "founders": ["Marcus Johnson"],
            "source": "YCombinator",
            "label": 1
        },
        {
            "name": "FashionAI",
            "description": "Fashion tech platform using AI for personalization. We revolutionize online shopping with virtual try-on and recommendations.",
            "industry": "Fashion Tech",
            "founded_year": 2022,
            "batch": "Spring 2022",
            "status": "Private",
            "team_size": 105,
            "location": "New York, NY",
            "founders": ["Natalie Scott"],
            "source": "YCombinator",
            "label": 1
        },
    ]
    
    # ===== NEGATIVE DATA (Non-YC Companies - Label: 0) =====
    NON_YC_COMPANIES_SYNTHETIC = [
        {
            "name": "LocalServices Pro",
            "description": "Small local service directory connecting customers with nearby service providers. Limited market reach and simple technology.",
            "industry": "Local Services",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 8,
            "location": "Austin, TX",
            "founders": ["Mike Johnson"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Community Garden App",
            "description": "Mobile app connecting urban gardeners. Niche market with limited scalability. Focuses on local community engagement only.",
            "industry": "Lifestyle",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 5,
            "location": "Portland, OR",
            "founders": ["Sarah Green"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Freelance Writer Hub",
            "description": "Platform connecting writers with clients. Highly fragmented market with many competitors. Minimal differentiation.",
            "industry": "Marketplace",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 12,
            "location": "Bangalore, India",
            "founders": ["Raj Patel"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Pet Grooming Scheduler",
            "description": "Booking system for pet grooming salons. Limited to pet services niche. Low barrier to entry with strong competition.",
            "industry": "Pet Services",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 6,
            "location": "Denver, CO",
            "founders": ["Emma Wilson"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Personal Fitness Tracker",
            "description": "Mobile fitness app tracking workouts. Saturated market with established players like Strava and MyFitnessPal.",
            "industry": "Fitness",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 9,
            "location": "Los Angeles, CA",
            "founders": ["Jason Lee"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Local Restaurant Reviews",
            "description": "Restaurant review platform for a single city. Competes with Yelp and Google Reviews. Limited market size.",
            "industry": "Reviews",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 7,
            "location": "Seattle, WA",
            "founders": ["Tom Brown"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "DIY Home Improvement Store",
            "description": "Online store selling DIY tools and materials. Heavy competition from Home Depot and Lowe's. No clear differentiation.",
            "industry": "E-commerce",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 15,
            "location": "Atlanta, GA",
            "founders": ["Richard Davis"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Music Lesson Platform",
            "description": "Connect music teachers with students online. Highly fragmented with many small competitors. Limited differentiation.",
            "industry": "EdTech",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 8,
            "location": "Nashville, TN",
            "founders": ["Lucy Nelson"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Event Planning Assistant",
            "description": "Event planning software for small event planners. Niche market with limited growth potential. Outdated technology.",
            "industry": "Events",
            "founded_year": 2016,
            "batch": "N/A",
            "status": "Private",
            "team_size": 6,
            "location": "Las Vegas, NV",
            "founders": ["Patricia White"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Photography Portfolio Site",
            "description": "Portfolio website builder for photographers. Redundant market with Wix and Squarespace. Minimal innovation.",
            "industry": "SaaS",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 5,
            "location": "Portland, ME",
            "founders": ["Chris Anderson"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Craft Beer Marketplace",
            "description": "Local craft beer delivery service. Limited geographic expansion. High operating costs.",
            "industry": "E-commerce",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 10,
            "location": "Boulder, CO",
            "founders": ["Kevin Miller"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Vintage Clothing Store",
            "description": "Online vintage clothing seller. Niche market with inconsistent supply. Difficult scalability.",
            "industry": "E-commerce",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 4,
            "location": "Portland, OR",
            "founders": ["Nina Martinez"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Corporate Gift Service",
            "description": "Custom corporate gift provider. B2B market but low margins. High customer acquisition cost.",
            "industry": "Services",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 9,
            "location": "Chicago, IL",
            "founders": ["Robert Kim"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Niche Travel Blog Network",
            "description": "Aggregator of travel blogs for specific destinations. Low differentiation from existing platforms.",
            "industry": "Travel",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 3,
            "location": "Portland, OR",
            "founders": ["Jennifer Smith"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Tutoring Marketplace",
            "description": "Platform connecting tutors with students for academic subjects. Overcrowded market with Chegg and Tutor.com.",
            "industry": "EdTech",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 11,
            "location": "Boston, MA",
            "founders": ["Amanda Lee"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "House Cleaning Booking",
            "description": "Booking system for house cleaning services. Highly local with limited scalability. Razor-thin margins.",
            "industry": "Services",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 7,
            "location": "Miami, FL",
            "founders": ["Isabella Garcia"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Small Business Accounting",
            "description": "Accounting software for freelancers. CompetesACE Quickbooks and FreshBooks. Difficult to differentiate.",
            "industry": "FinTech",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 12,
            "location": "San Diego, CA",
            "founders": ["Michael Chang"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Local Delivery Service",
            "description": "Same-day delivery for local merchants. Competes with DoorDash and Uber Eats. High burn rate.",
            "industry": "Logistics",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 25,
            "location": "Phoenix, AZ",
            "founders": ["David Santos"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Pet Sitting Network",
            "description": "Connect pet owners with pet sitters. Niche market with intense local competition from Rover.",
            "industry": "Pet Services",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 6,
            "location": "Austin, TX",
            "founders": ["Sarah Thompson"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Yoga Class Booking",
            "description": "Simple booking system for yoga studios. Very niche with minimal differentiation.",
            "industry": "Wellness",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 5,
            "location": "Los Angeles, CA",
            "founders": ["Yoga Teacher Lisa"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Handmade Crafts Store",
            "description": "Online marketplace for handmade items. Competes with Etsy with no clear advantage.",
            "industry": "E-commerce",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 4,
            "location": "Brooklyn, NY",
            "founders": ["Maya Patel"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Local Job Board",
            "description": "Job listing site for a single city. Insignificant scale compared to Indeed and LinkedIn.",
            "industry": "HR Tech",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 8,
            "location": "Dallas, TX",
            "founders": ["James Wilson"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Academic Paper Formatter",
            "description": "Tool to format academic papers. Limited market and redundant with existing tools.",
            "industry": "SaaS",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 3,
            "location": "Cambridge, MA",
            "founders": ["Dr. Robert Evans"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Plant Identification App",
            "description": "Mobile app to identify plants using photos. Hobby project with limited commercial potential.",
            "industry": "Consumer App",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 2,
            "location": "Asheville, NC",
            "founders": ["Emma Green"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Coupon Aggregator",
            "description": "Website collecting coupons from retailers. Passive income project with minimal value add.",
            "industry": "Consumer Services",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 2,
            "location": "Denver, CO",
            "founders": ["Coupon Hunter Bob"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Blog About Tech",
            "description": "Technology blog covering news and reviews. Saturated market with no unique perspective.",
            "industry": "Media",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 3,
            "location": "San Francisco, CA",
            "founders": ["Tech Blogger John"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Dropshipping Store",
            "description": "Dropshipping e-commerce store reselling generic products. Extremely low barriers to entry and differentiation.",
            "industry": "E-commerce",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 1,
            "location": "Unknown",
            "founders": ["Anonymous Seller"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Email Newsletter Service",
            "description": "Email template builder for newsletters. Redundant with MailChimp and Substack.",
            "industry": "SaaS",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 4,
            "location": "Austin, TX",
            "founders": ["David Brown"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Resume Builder",
            "description": "Online tool to create resumes. Crowded market with Canva, Indeed, and dozens of others.",
            "industry": "SaaS",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 5,
            "location": "Seattle, WA",
            "founders": ["Career Coach Sara"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Niche Forum Community",
            "description": "Online forum for enthusiasts of a specific hobby. Limited network effects and declining forum traffic.",
            "industry": "Social Media",
            "founded_year": 2015,
            "batch": "N/A",
            "status": "Private",
            "team_size": 2,
            "location": "Portland, OR",
            "founders": ["Forum Moderator Steve"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Local Weather App",
            "description": "Weather application with local forecasts. Redundant with existing Weather.com and native OS apps.",
            "industry": "Consumer App",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 3,
            "location": "Boulder, CO",
            "founders": ["Weather Enthusiast Tom"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Apartment Rental Platform",
            "description": "Apartment listing aggregator for a single city. Competes with Zillow and Craigslist with no advantage.",
            "industry": "Real Estate",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 6,
            "location": "Austin, TX",
            "founders": ["Landlord Larry"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Movie Review Aggregator",
            "description": "Website aggregating movie reviews. Redundant with IMDB and Rotten Tomatoes.",
            "industry": "Media",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 2,
            "location": "Los Angeles, CA",
            "founders": ["Film Buff Marcus"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Stock Tips Newsletter",
            "description": "Email newsletter with stock trading tips. Unaccredited advice with legal liability.",
            "industry": "Finance",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 1,
            "location": "Wall Street",
            "founders": ["Day Trader Joe"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Noisy Neighborhood Forum",
            "description": "Neighborhood social network for local issues. Ultra-niche with minimal expansion potential.",
            "industry": "Social Media",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 3,
            "location": "Portland, OR",
            "founders": ["Neighborhood Hero"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Recipe Collection App",
            "description": "App to save and organize recipes. Heavily fragmented market with thousands of competitors.",
            "industry": "Consumer App",
            "founded_year": 2020,
            "batch": "N/A",
            "status": "Private",
            "team_size": 2,
            "location": "Austin, TX",
            "founders": ["Home Chef Alex"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Expense Tracker",
            "description": "Personal expense tracking app. Saturated market with Mint, YNAB, and dozens of others.",
            "industry": "FinTech",
            "founded_year": 2018,
            "batch": "N/A",
            "status": "Private",
            "team_size": 4,
            "location": "Denver, CO",
            "founders": ["Budget Conscious Brian"],
            "source": "Wellfound",
            "label": 0
        },
        {
            "name": "Reading List Manager",
            "description": "App to manage personal reading lists. Nice-to-have tool with weak monetization.",
            "industry": "Consumer App",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 1,
            "location": "Seattle, WA",
            "founders": ["Book Lover Lisa"],
            "source": "IndieHackers",
            "label": 0
        },
        {
            "name": "Password Manager",
            "description": "Password management tool. Dominated by 1Password, Bitwarden, and LastPass.",
            "industry": "Security",
            "founded_year": 2017,
            "batch": "N/A",
            "status": "Private",
            "team_size": 3,
            "location": "San Francisco, CA",
            "founders": ["Security Expert Chris"],
            "source": "AngelList",
            "label": 0
        },
        {
            "name": "Side Hustle Job Board",
            "description": "Platform for side gigs and freelance work. Competes with Fiverr and Upwork but with no differentiation.",
            "industry": "Marketplace",
            "founded_year": 2019,
            "batch": "N/A",
            "status": "Private",
            "team_size": 5,
            "location": "Los Angeles, CA",
            "founders": ["Freelance King Marcus"],
            "source": "Wellfound",
            "label": 0
        },
    ]
    
    def __init__(self):
        """Initialize synthetic data generator."""
        log.info("✓ SyntheticDataGenerator initialized with 100 companies")
    
    def generate_dataset(self) -> pd.DataFrame:
        """
        Generate complete synthetic dataset.
        
        Returns:
            DataFrame with 100 companies (50 YC + 50 non-YC)
        """
        log.info("Generating synthetic dataset...")
        
        # Combine YC and non-YC data
        all_data = self.YC_COMPANIES_SYNTHETIC + self.NON_YC_COMPANIES_SYNTHETIC
        
        # Create DataFrame
        df = pd.DataFrame(all_data)
        
        # Ensure all required columns exist
        required_cols = ['name', 'description', 'industry', 'source', 'label']
        for col in required_cols:
            if col not in df.columns:
                df[col] = 'Unknown'
        
        # Remove duplicates
        df = df.drop_duplicates(subset=['name'])
        
        log.info(f"✓ Generated dataset shape: {df.shape}")
        log.info(f"  Positive (YC): {(df['label'] == 1).sum()}")
        log.info(f"  Negative (Non-YC): {(df['label'] == 0).sum()}")
        
        return df